posts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('single/<str:title>/', views.singular_post, name='post'),
    path('submit_comment/', views.submit_comment, name='submit_comment'),
    path('upload_file', views.upload_something, name='upload_file'),
    path('uploaded_files',views.test_upload, name='file_upload'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techblog/urls.py
from django.contrib import admin
from django.urls import include, path
from posts import views
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('user_management.urls')),
    path('posts/', include('posts.urls')),
    path('', views.index),
    path('about/', views.about, name='about'),
    path('admin/', admin.site.urls),
]

user_management/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register, name='register')
]

posts/models.py
from django.db import models
from django.contrib import admin
import os
# Create your models here.

class StandardTextPost(models.Model):
    title = models.CharField(max_length=200)
    blog_text = models.CharField(max_length=10000)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.title
    def short_text(self):
        return self.blog_text[:50] + "..."

class Comment(models.Model):
    post = models.ForeignKey('StandardTextPost', on_delete=models.CASCADE,)
    comment = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.comment

class PostWithUploads(models.Model):
    post = models.CharField(max_length=500)
    file = models.FileField()

    def filename(self):
        return os.path.basename(self.file.name)

user_management/models.py
from django.db import models

# Create your models here.

posts/views.py
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import StandardTextPost,Comment,PostWithUploads
from django.template import loader
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404
import os

def index(request):
    post_list = StandardTextPost.objects.order_by('-pub_date')
    template = loader.get_template('posts/index.html')
    context = {
        'post_list': post_list,
    }
    return HttpResponse(template.render(context, request))

def about(request):
    return HttpResponse("Tää on vähän tyhjä vielä")

def singular_post(request, title):
    try:
        post = StandardTextPost.objects.get(pk=title)
    except ObjectDoesNotExist:
        pass
    try:
        comments = Comment.objects.filter(post=post).order_by('pub_date')
    except ObjectDoesNotExist:
        pass
    template = loader.get_template('posts/single_full_post.html')
    context = {
        'post': post,
        'comments': comments,
    }
    return HttpResponse(template.render(context, request))

def submit_comment(request):
    comment = Comment(post=StandardTextPost.objects.get(pk=request.POST['title']),comment=request.POST['username'] + ': ' + request.POST['comment'], pub_date=timezone.now())
    comment.save()
    return HttpResponseRedirect('/posts/single/' + request.POST['title'] + '/')

def submit_blog_post(request, submit):
    return HttpResponse("jee!")

def test_upload(request):
    #path="/var/lib/techblog/posts/static/uploads"
    #img_list = os.listdir(path)
    description = PostWithUploads.objects.order_by('file')
    template = loader.get_template('gallery.html')
    context = {
        #'images': img_list,
        'descriptions': description,
    }
    return HttpResponse(template.render(context, request))

def upload_something(request):
    if request.method == 'POST':
        if request.user.is_authenticated and request.user.is_superuser:
            uploaded_file = request.FILES['document']
            post = request.POST['description']
            new_upload = PostWithUploads(post=post,file=uploaded_file)
            new_upload.save()
        return HttpResponseRedirect('/posts/upload_file')
    return render(request, 'upload.html')

techblog/views.py
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404
import os


def about(request):
    return HttpResponse("Tää on vähän tyhjä vielä")

user_management/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()

    context = {'form' : form}
    return render(request, 'registration/register.html', context)

posts/templates/gallery.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">
{% include "posts/sidebar.html" %}
<div class="main">
{% for description in descriptions %}
<p> {{description.post}} </p>
<img src="{{description.file.url }}" />
{% endfor %}
</div>

posts/templates/posts/index.html
{% include "posts/sidebar.html" %}
{% load static %}
<div class="main">
<link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">
<h1> Tech-Blog about DevOps and stuff by Juho Rönkkö </h1><br>
{% if post_list %}
    {% for post in post_list %}
    <h>{{ post.title }} ({{post.pub_date}})</h>
        <p>{{ post.short_text }}</p>
    	<a href="{% url 'posts:post' post.id %}">Full text</a>
    <br>
    {% endfor %}
{% else %}
    <p>No posts are available.</p>
{% endif %}
</div>

posts/templates/posts/sidebar.html
{% load static %}
<div class="sidenav"> 
  <img src="{% static "posts/images/mina.jpg" %}"><br>
  <a href="{% url 'about' %}">About</a>
  <a href="{% url 'posts:index' %}">Posts</a>
  <a target="_blank" rel="noopener noreferrer" href="https://github.com/Julumettu">GitHub</a>
  {% if user.is_authenticated %}
  <p1> Logged in as {{ user.username }}</p1>
  {% if user.is_superuser %}
  <a href="/posts/upload_file">Upload files</a>
  {% endif %}
  <a href="/accounts/logout">Logout</a>
  {% else %}
  <a href="/accounts/login">Login</a>
  <a href="/register">Registration</a>
  {% endif %}
</div>

posts/templates/posts/single_full_post.html
{% include "posts/sidebar.html" %} 
{% load static %}

<div class="main">
<link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">

{% if post %}
	<h>{{ post.title }}</h>
        <p>{{ post.blog_text }}</p>
	<p>{{ post.pub_date }} </p>
    	<a href="{% url 'posts:index' %}">Back to front page</a>
{% endif %}
<form action="{% url 'posts:submit_comment' %}" method="post">
{% csrf_token %}
    {% if user.is_authenticated %}
    <label for="comment">Leave a comment </label><br>
    <input type="text" name="comment" value="">
    <input type="hidden" name="title" value="{{ post.id }}">
    <input type="hidden" name="username" value="{{ user.username }}">
    <input type="submit" value="Send">
    {% else %}
    	<p>You must be logged in to comment</p>
	<p> Click here to <a href="/accounts/login">Login</a> </p>
	<p> Or here to  <a href="/register">Registration</a> </p>
    {% endif %}
</form>
{% if comments %}
    <div class="comments">
    {% for comment in comments %}
    <p>{{ comment.comment }}</p>
    <p>{{ comment.pub_date }}</p>
    {% endfor %}
    </div>
{% else %}
    <p>There are no comments here! :( Maybe you could leave one?</p>
{% endif %}
</div>

posts/templates/upload.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">
{% include "posts/sidebar.html" %}
<div class="main">
<h> Upload some files </h>
<form action="{% url 'posts:upload_file' %}" enctype="multipart/form-data" method="post">
{% csrf_token %}
    {% if user.is_authenticated and user.is_superuser %}
    <input type="text" name="description">
    <input type="file" name="document">
    <input type="submit" value="Send">
    {% else %}
        <p>You must be logged in with admin user to upload something</p>
        <a href="/accounts/login">Login</a>
    {% endif %}
</form>
</div>